/**
 * Top 100 US Cities and their States
 */
export const US_CITIES = [
  { city: "New York", state: "NY" },
  { city: "Los Angeles", state: "CA" },
  { city: "Chicago", state: "IL" },
  { city: "Houston", state: "TX" },
  { city: "Phoenix", state: "AZ" },
  { city: "Philadelphia", state: "PA" },
  { city: "San Antonio", state: "TX" },
  { city: "San Diego", state: "CA" },
  { city: "Dallas", state: "TX" },
  { city: "San Jose", state: "CA" },
  { city: "Austin", state: "TX" },
  { city: "Jacksonville", state: "FL" },
  { city: "Fort Worth", state: "TX" },
  { city: "Columbus", state: "OH" },
  { city: "San Francisco", state: "CA" },
  { city: "Charlotte", state: "NC" },
  { city: "Indianapolis", state: "IN" },
  { city: "Seattle", state: "WA" },
  { city: "Denver", state: "CO" },
  { city: "Washington", state: "DC" },
  { city: "Boston", state: "MA" },
  { city: "El Paso", state: "TX" },
  { city: "Nashville", state: "TN" },
  { city: "Detroit", state: "MI" },
  { city: "Oklahoma City", state: "OK" },
  { city: "Portland", state: "OR" },
  { city: "Las Vegas", state: "NV" },
  { city: "Memphis", state: "TN" },
  { city: "Louisville", state: "KY" },
  { city: "Baltimore", state: "MD" },
  { city: "Milwaukee", state: "WI" },
  { city: "Albuquerque", state: "NM" },
  { city: "Tucson", state: "AZ" },
  { city: "Fresno", state: "CA" },
  { city: "Sacramento", state: "CA" },
  { city: "Mesa", state: "AZ" },
  { city: "Kansas City", state: "MO" },
  { city: "Atlanta", state: "GA" },
  { city: "Long Beach", state: "CA" },
  { city: "Colorado Springs", state: "CO" },
  { city: "Raleigh", state: "NC" },
  { city: "Miami", state: "FL" },
  { city: "Virginia Beach", state: "VA" },
  { city: "Omaha", state: "NE" },
  { city: "Oakland", state: "CA" },
  { city: "Minneapolis", state: "MN" },
  { city: "Tulsa", state: "OK" },
  { city: "Wichita", state: "KS" },
  { city: "New Orleans", state: "LA" },
  { city: "Arlington", state: "TX" },
  { city: "Cleveland", state: "OH" },
  { city: "Bakersfield", state: "CA" },
  { city: "Tampa", state: "FL" },
  { city: "Aurora", state: "CO" },
  { city: "Honolulu", state: "HI" },
  { city: "Anaheim", state: "CA" },
  { city: "Santa Ana", state: "CA" },
  { city: "Corpus Christi", state: "TX" },
  { city: "Riverside", state: "CA" },
  { city: "Lexington", state: "KY" },
  { city: "St. Louis", state: "MO" },
  { city: "Stockton", state: "CA" },
  { city: "Pittsburgh", state: "PA" },
  { city: "Saint Paul", state: "MN" },
  { city: "Cincinnati", state: "OH" },
  { city: "Anchorage", state: "AK" },
  { city: "Henderson", state: "NV" },
  { city: "Greensboro", state: "NC" },
  { city: "Plano", state: "TX" },
  { city: "Newark", state: "NJ" },
  { city: "Lincoln", state: "NE" },
  { city: "Orlando", state: "FL" },
  { city: "Irvine", state: "CA" },
  { city: "Toledo", state: "OH" },
  { city: "Jersey City", state: "NJ" },
  { city: "Chula Vista", state: "CA" },
  { city: "Durham", state: "NC" },
  { city: "Fort Wayne", state: "IN" },
  { city: "St. Petersburg", state: "FL" },
  { city: "Laredo", state: "TX" },
  { city: "Madison", state: "WI" },
  { city: "Chandler", state: "AZ" },
  { city: "Buffalo", state: "NY" },
  { city: "Lubbock", state: "TX" },
  { city: "Scottsdale", state: "AZ" },
  { city: "Reno", state: "NV" },
  { city: "Glendale", state: "AZ" },
  { city: "Gilbert", state: "AZ" },
  { city: "Winston-Salem", state: "NC" },
  { city: "North Las Vegas", state: "NV" },
  { city: "Norfolk", state: "VA" },
  { city: "Chesapeake", state: "VA" },
  { city: "Garland", state: "TX" },
  { city: "Irving", state: "TX" },
  { city: "Hialeah", state: "FL" },
  { city: "Fremont", state: "CA" },
  { city: "Boise", state: "ID" },
  { city: "Richmond", state: "VA" },
  { city: "Spokane", state: "WA" },
  { city: "Baton Rouge", state: "LA" }
];

/**
 * Niche to Geoapify Categories mapping
 */
export const NICHE_CATEGORIES: Record<string, string> = {
  "Dentist": "healthcare.dentist",
  "Restaurant": "catering.restaurant",
  "Lawyer": "service.financial,service.financial.lawyer,office",
  "Gym": "leisure.sport,leisure.sport.fitness",
  "Plumber": "service.construction,service.construction.plumbing",
  "Electrician": "service.construction,service.construction.electrical",
  "HVAC": "service.construction,service.construction.hvac",
  "Roofer": "service.construction,service.construction.roofing",
  "Real Estate": "service.real_estate",
  "Pet Care": "service.animal,service.animal.veterinary",
  "Auto Repair": "service.vehicle,service.vehicle.repair",
  "Daycare": "childcare",
  "Cleaning Service": "service.cleaning",
  "Spa & Salon": "healthcare.health_and_beauty,healthcare.health_and_beauty.spa,healthcare.health_and_beauty.hairdresser"
};

export const NICHES = Object.keys(NICHE_CATEGORIES);
